apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - /bin/sh
          - "-c"
          - "while true; do sleep 10; echo ZZZZ; done"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      # Tolerate the ACI taint to get the scheduler to schedule it.
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
